benchmarks:
  mc:
    K_max: 20
    input_range:
    - -0.5
    - 0.5
    sequence_length: 1000
input:
  base_rate: 10.0
  input_density: 0.3
  input_gain: 40.0
  input_weight: 15.0
  n_fibers_per_input: 4
  protocol: poisson
  symbol_duration: 30.0
integration:
  dt: 0.01
  method: rk4
network:
  N: 150
  connection_prob: 0.2
  ei_ratio: 0.8
  spectral_radius: 10.0
  w_exc_mean: 1.2
  w_inh_mean: 6.0
neuron:
  C_m: 1.0
  E_K: -77.0
  E_L: -54.4
  E_Na: 50.0
  V_rest: -65.0
  g_K: 36.0
  g_L: 0.3
  g_Na: 120.0
  model: hh
readout:
  test_fraction: 0.15
  train_fraction: 0.7
  val_fraction: 0.15
simulation:
  downsample_rates: 10
  washout: 1000.0
synapse:
  model: current
  tau_exc: 5.0
  tau_inh: 10.0
